// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbq

import (
	"context"
	"database/sql"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT count(*) FROM api_keys WHERE revoked_at IS NULL
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAPIKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, name, scopes, secret_hash, created_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID         string
	Name       string
	Scopes     string
	SecretHash []byte
	CreatedBy  sql.NullString
	CreatedAt  int64
	ExpiresAt  sql.NullInt64
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.SecretHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, scopes, secret_hash, previous_secret_hash, previous_expires_at, created_by, created_at, rotated_at, last_used_at, expires_at, revoked_at FROM api_keys WHERE id = ?
`

func (q *Queries) GetAPIKey(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scopes,
		&i.SecretHash,
		&i.PreviousSecretHash,
		&i.PreviousExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, scopes, secret_hash, previous_secret_hash, previous_expires_at, created_by, created_at, rotated_at, last_used_at, expires_at, revoked_at FROM api_keys
WHERE CAST(?1 AS BOOLEAN) OR revoked_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListAPIKeys(ctx context.Context, includeRevoked bool) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, includeRevoked)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scopes,
			&i.SecretHash,
			&i.PreviousSecretHash,
			&i.PreviousExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	RevokedAt sql.NullInt64
	ID        string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rotateAPIKey = `-- name: RotateAPIKey :exec
UPDATE api_keys
SET previous_secret_hash = CASE WHEN ?1 IS NULL THEN NULL ELSE secret_hash END,
    previous_expires_at  = ?1,
    secret_hash          = ?2,
    rotated_at           = ?3
WHERE id = ?4
`

type RotateAPIKeyParams struct {
	GraceUntil sql.NullInt64
	SecretHash []byte
	RotatedAt  sql.NullInt64
	ID         string
}

func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, rotateAPIKey,
		arg.GraceUntil,
		arg.SecretHash,
		arg.RotatedAt,
		arg.ID,
	)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = ? WHERE id = ?
`

type TouchAPIKeyParams struct {
	LastUsedAt sql.NullInt64
	ID         string
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, arg.LastUsedAt, arg.ID)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys SET name = ?, scopes = ?, expires_at = ? WHERE id = ?
`

type UpdateAPIKeyParams struct {
	Name      string
	Scopes    string
	ExpiresAt sql.NullInt64
	ID        string
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey,
		arg.Name,
		arg.Scopes,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
