// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbq

import (
	"context"
	"database/sql"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (at, actor_key_id, actor_user, action, target, detail, client_ip)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	At         int64
	ActorKeyID sql.NullString
	ActorUser  sql.NullString
	Action     string
	Target     sql.NullString
	Detail     sql.NullString
	ClientIp   sql.NullString
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.At,
		arg.ActorKeyID,
		arg.ActorUser,
		arg.Action,
		arg.Target,
		arg.Detail,
		arg.ClientIp,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, at, actor_key_id, "action", target, detail, client_ip, actor_user FROM audit_events
WHERE (action = ?1 OR ?1 IS NULL)
  AND (actor_key_id = ?2 OR ?2 IS NULL)
  AND (actor_user = ?3 OR ?3 IS NULL)
  AND (id < ?4 OR ?4 IS NULL)
ORDER BY id DESC
LIMIT ?5
`

type ListAuditEventsParams struct {
	Action     sql.NullString
	ActorKeyID sql.NullString
	ActorUser  sql.NullString
	BeforeID   sql.NullInt64
	Limit      int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents,
		arg.Action,
		arg.ActorKeyID,
		arg.ActorUser,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorKeyID,
			&i.Action,
			&i.Target,
			&i.Detail,
			&i.ClientIp,
			&i.ActorUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
