// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbq

import (
	"context"
	"database/sql"
)

const cancelJob = `-- name: CancelJob :execrows
UPDATE jobs SET status = 'canceled', finished_at = ?
WHERE id = ? AND status = 'queued'
`

type CancelJobParams struct {
	FinishedAt sql.NullInt64
	ID         int64
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelJob, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'printing', started_at = ?1, attempts = attempts + 1
WHERE id = (
    SELECT id FROM jobs WHERE status = 'queued'
    ORDER BY priority DESC, id LIMIT 1
)
RETURNING id, payload, copies
`

type ClaimNextJobRow struct {
	ID      int64
	Payload []byte
	Copies  int64
}

func (q *Queries) ClaimNextJob(ctx context.Context, startedAt sql.NullInt64) (ClaimNextJobRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob, startedAt)
	var i ClaimNextJobRow
	err := row.Scan(&i.ID, &i.Payload, &i.Copies)
	return i, err
}

const countJobsByStatus = `-- name: CountJobsByStatus :many
SELECT status, count(*) AS count FROM jobs GROUP BY status
`

type CountJobsByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountJobsByStatus(ctx context.Context) ([]CountJobsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countJobsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByStatusRow{}
	for rows.Next() {
		var i CountJobsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    kind, priority, label, copies, api_key_id, username, client_ip, user_agent,
    content_type, source, source_size, payload, payload_size, payload_sha256,
    retry_of, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateJobParams struct {
	Kind          string
	Priority      int64
	Label         sql.NullString
	Copies        int64
	ApiKeyID      sql.NullString
	Username      sql.NullString
	ClientIp      sql.NullString
	UserAgent     sql.NullString
	ContentType   sql.NullString
	Source        []byte
	SourceSize    int64
	Payload       []byte
	PayloadSize   int64
	PayloadSha256 string
	RetryOf       sql.NullInt64
	CreatedAt     int64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.Kind,
		arg.Priority,
		arg.Label,
		arg.Copies,
		arg.ApiKeyID,
		arg.Username,
		arg.ClientIp,
		arg.UserAgent,
		arg.ContentType,
		arg.Source,
		arg.SourceSize,
		arg.Payload,
		arg.PayloadSize,
		arg.PayloadSha256,
		arg.RetryOf,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const failInterruptedJobs = `-- name: FailInterruptedJobs :execrows
UPDATE jobs
SET status = 'failed', error = 'interrupted: the server stopped while the job was printing', finished_at = ?
WHERE status = 'printing'
`

func (q *Queries) FailInterruptedJobs(ctx context.Context, finishedAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, failInterruptedJobs, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs
SET status = ?1, error = ?2,
    confirmed = ?3, finished_at = ?4
WHERE id = ?5
`

type FinishJobParams struct {
	Status     string
	Error      sql.NullString
	Confirmed  int64
	FinishedAt sql.NullInt64
	ID         int64
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.Confirmed,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, status, priority, label, copies, api_key_id, username,
       client_ip, user_agent, content_type, source_size, payload_size, payload_sha256,
       attempts, error, confirmed, retry_of, created_at, started_at,
       finished_at, purged_at
FROM jobs WHERE id = ?
`

type GetJobRow struct {
	ID            int64
	Kind          string
	Status        string
	Priority      int64
	Label         sql.NullString
	Copies        int64
	ApiKeyID      sql.NullString
	Username      sql.NullString
	ClientIp      sql.NullString
	UserAgent     sql.NullString
	ContentType   sql.NullString
	SourceSize    int64
	PayloadSize   int64
	PayloadSha256 string
	Attempts      int64
	Error         sql.NullString
	Confirmed     int64
	RetryOf       sql.NullInt64
	CreatedAt     int64
	StartedAt     sql.NullInt64
	FinishedAt    sql.NullInt64
	PurgedAt      sql.NullInt64
}

func (q *Queries) GetJob(ctx context.Context, id int64) (GetJobRow, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.Priority,
		&i.Label,
		&i.Copies,
		&i.ApiKeyID,
		&i.Username,
		&i.ClientIp,
		&i.UserAgent,
		&i.ContentType,
		&i.SourceSize,
		&i.PayloadSize,
		&i.PayloadSha256,
		&i.Attempts,
		&i.Error,
		&i.Confirmed,
		&i.RetryOf,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.PurgedAt,
	)
	return i, err
}

const getJobForRetry = `-- name: GetJobForRetry :one
SELECT kind, priority, label, copies, content_type, source, source_size,
       payload, payload_size, payload_sha256
FROM jobs WHERE id = ?
`

type GetJobForRetryRow struct {
	Kind          string
	Priority      int64
	Label         sql.NullString
	Copies        int64
	ContentType   sql.NullString
	Source        []byte
	SourceSize    int64
	Payload       []byte
	PayloadSize   int64
	PayloadSha256 string
}

func (q *Queries) GetJobForRetry(ctx context.Context, id int64) (GetJobForRetryRow, error) {
	row := q.db.QueryRowContext(ctx, getJobForRetry, id)
	var i GetJobForRetryRow
	err := row.Scan(
		&i.Kind,
		&i.Priority,
		&i.Label,
		&i.Copies,
		&i.ContentType,
		&i.Source,
		&i.SourceSize,
		&i.Payload,
		&i.PayloadSize,
		&i.PayloadSha256,
	)
	return i, err
}

const getJobPayload = `-- name: GetJobPayload :one
SELECT payload FROM jobs WHERE id = ?
`

func (q *Queries) GetJobPayload(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getJobPayload, id)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const getJobSource = `-- name: GetJobSource :one
SELECT source, content_type FROM jobs WHERE id = ?
`

type GetJobSourceRow struct {
	Source      []byte
	ContentType sql.NullString
}

func (q *Queries) GetJobSource(ctx context.Context, id int64) (GetJobSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getJobSource, id)
	var i GetJobSourceRow
	err := row.Scan(&i.Source, &i.ContentType)
	return i, err
}

const hasQueuedJobs = `-- name: HasQueuedJobs :one
SELECT EXISTS (SELECT 1 FROM jobs WHERE status = 'queued')
`

func (q *Queries) HasQueuedJobs(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasQueuedJobs)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, status, priority, label, copies, api_key_id, username,
       client_ip, user_agent, content_type, source_size, payload_size, payload_sha256,
       attempts, error, confirmed, retry_of, created_at, started_at,
       finished_at, purged_at
FROM jobs
WHERE (status = ?1 OR ?1 IS NULL)
  AND (kind = ?2 OR ?2 IS NULL)
  AND (api_key_id = ?3 OR ?3 IS NULL)
  AND (username = ?4 OR ?4 IS NULL)
  AND (id < ?5 OR ?5 IS NULL)
  AND (created_at >= ?6 OR ?6 IS NULL)
ORDER BY id DESC
LIMIT ?7
`

type ListJobsParams struct {
	Status   sql.NullString
	Kind     sql.NullString
	ApiKeyID sql.NullString
	Username sql.NullString
	BeforeID sql.NullInt64
	Since    sql.NullInt64
	Limit    int64
}

type ListJobsRow struct {
	ID            int64
	Kind          string
	Status        string
	Priority      int64
	Label         sql.NullString
	Copies        int64
	ApiKeyID      sql.NullString
	Username      sql.NullString
	ClientIp      sql.NullString
	UserAgent     sql.NullString
	ContentType   sql.NullString
	SourceSize    int64
	PayloadSize   int64
	PayloadSha256 string
	Attempts      int64
	Error         sql.NullString
	Confirmed     int64
	RetryOf       sql.NullInt64
	CreatedAt     int64
	StartedAt     sql.NullInt64
	FinishedAt    sql.NullInt64
	PurgedAt      sql.NullInt64
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobs,
		arg.Status,
		arg.Kind,
		arg.ApiKeyID,
		arg.Username,
		arg.BeforeID,
		arg.Since,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsRow{}
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Priority,
			&i.Label,
			&i.Copies,
			&i.ApiKeyID,
			&i.Username,
			&i.ClientIp,
			&i.UserAgent,
			&i.ContentType,
			&i.SourceSize,
			&i.PayloadSize,
			&i.PayloadSha256,
			&i.Attempts,
			&i.Error,
			&i.Confirmed,
			&i.RetryOf,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedJobs = `-- name: ListQueuedJobs :many
SELECT id, kind, status, priority, label, copies, api_key_id, username,
       client_ip, user_agent, content_type, source_size, payload_size, payload_sha256,
       attempts, error, confirmed, retry_of, created_at, started_at,
       finished_at, purged_at
FROM jobs WHERE status = 'queued'
ORDER BY priority DESC, id
LIMIT ?
`

type ListQueuedJobsRow struct {
	ID            int64
	Kind          string
	Status        string
	Priority      int64
	Label         sql.NullString
	Copies        int64
	ApiKeyID      sql.NullString
	Username      sql.NullString
	ClientIp      sql.NullString
	UserAgent     sql.NullString
	ContentType   sql.NullString
	SourceSize    int64
	PayloadSize   int64
	PayloadSha256 string
	Attempts      int64
	Error         sql.NullString
	Confirmed     int64
	RetryOf       sql.NullInt64
	CreatedAt     int64
	StartedAt     sql.NullInt64
	FinishedAt    sql.NullInt64
	PurgedAt      sql.NullInt64
}

// Queued jobs in the order they will print.
func (q *Queries) ListQueuedJobs(ctx context.Context, limit int64) ([]ListQueuedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueuedJobsRow{}
	for rows.Next() {
		var i ListQueuedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Priority,
			&i.Label,
			&i.Copies,
			&i.ApiKeyID,
			&i.Username,
			&i.ClientIp,
			&i.UserAgent,
			&i.ContentType,
			&i.SourceSize,
			&i.PayloadSize,
			&i.PayloadSha256,
			&i.Attempts,
			&i.Error,
			&i.Confirmed,
			&i.RetryOf,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeJobData = `-- name: PurgeJobData :execrows
UPDATE jobs SET source = NULL, payload = NULL, purged_at = ?1
WHERE purged_at IS NULL AND status IN ('completed', 'failed', 'canceled')
  AND finished_at < ?2
`

type PurgeJobDataParams struct {
	Now    sql.NullInt64
	Before sql.NullInt64
}

func (q *Queries) PurgeJobData(ctx context.Context, arg PurgeJobDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeJobData, arg.Now, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queuePosition = `-- name: QueuePosition :one
SELECT count(*) FROM jobs q, jobs j
WHERE j.id = ?1 AND q.status = 'queued' AND q.id != j.id
  AND (q.priority > j.priority OR (q.priority = j.priority AND q.id < j.id))
`

// The number of queued jobs that will print before the given one.
func (q *Queries) QueuePosition(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, queuePosition, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}
