// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql"
)

type ApiKey struct {
	ID                 string
	Name               string
	Scopes             string
	SecretHash         []byte
	PreviousSecretHash []byte
	PreviousExpiresAt  sql.NullInt64
	CreatedBy          sql.NullString
	CreatedAt          int64
	RotatedAt          sql.NullInt64
	LastUsedAt         sql.NullInt64
	ExpiresAt          sql.NullInt64
	RevokedAt          sql.NullInt64
}

type AuditEvent struct {
	ID         int64
	At         int64
	ActorKeyID sql.NullString
	Action     string
	Target     sql.NullString
	Detail     sql.NullString
	ClientIp   sql.NullString
}

type Job struct {
	ID            int64
	Kind          string
	Status        string
	Priority      int64
	Label         sql.NullString
	Copies        int64
	ApiKeyID      sql.NullString
	ClientIp      sql.NullString
	UserAgent     sql.NullString
	ContentType   sql.NullString
	Source        []byte
	SourceSize    int64
	Payload       []byte
	PayloadSize   int64
	PayloadSha256 string
	Attempts      int64
	Error         sql.NullString
	Confirmed     int64
	RetryOf       sql.NullInt64
	CreatedAt     int64
	StartedAt     sql.NullInt64
	FinishedAt    sql.NullInt64
	PurgedAt      sql.NullInt64
}
