// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbq

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, created_at, expires_at, last_seen_at, client_ip, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	TokenHash  []byte
	UserID     int64
	CreatedAt  int64
	ExpiresAt  int64
	LastSeenAt int64
	ClientIp   sql.NullString
	UserAgent  sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.ClientIp,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, scopes, root, created_by, created_at, updated_at, password_changed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, username, password_hash, scopes, root, created_by, created_at, updated_at, password_changed_at, last_login_at, disabled_at
`

type CreateUserParams struct {
	Username          string
	PasswordHash      string
	Scopes            string
	Root              int64
	CreatedBy         sql.NullString
	CreatedAt         int64
	UpdatedAt         int64
	PasswordChangedAt int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Scopes,
		arg.Root,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PasswordChangedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Scopes,
		&i.Root,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = ?1
  AND (token_hash != ?2 OR ?2 IS NULL)
`

type DeleteUserSessionsParams struct {
	UserID int64
	Keep   []byte
}

func (q *Queries) DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserSessions, arg.UserID, arg.Keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRootUser = `-- name: GetRootUser :one
SELECT id, username, password_hash, scopes, root, created_by, created_at, updated_at, password_changed_at, last_login_at, disabled_at FROM users WHERE root = 1
`

func (q *Queries) GetRootUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getRootUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Scopes,
		&i.Root,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT sessions.token_hash, sessions.user_id, sessions.created_at, sessions.expires_at, sessions.last_seen_at, sessions.client_ip, sessions.user_agent, users.id, users.username, users.password_hash, users.scopes, users.root, users.created_by, users.created_at, users.updated_at, users.password_changed_at, users.last_login_at, users.disabled_at
FROM sessions JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = ?
`

type GetSessionRow struct {
	Session Session
	User    User
}

func (q *Queries) GetSession(ctx context.Context, tokenHash []byte) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, tokenHash)
	var i GetSessionRow
	err := row.Scan(
		&i.Session.TokenHash,
		&i.Session.UserID,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.Session.LastSeenAt,
		&i.Session.ClientIp,
		&i.Session.UserAgent,
		&i.User.ID,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.Scopes,
		&i.User.Root,
		&i.User.CreatedBy,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.PasswordChangedAt,
		&i.User.LastLoginAt,
		&i.User.DisabledAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, scopes, root, created_by, created_at, updated_at, password_changed_at, last_login_at, disabled_at FROM users WHERE username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Scopes,
		&i.Root,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, scopes, root, created_by, created_at, updated_at, password_changed_at, last_login_at, disabled_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Scopes,
		&i.Root,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.DisabledAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, scopes, root, created_by, created_at, updated_at, password_changed_at, last_login_at, disabled_at FROM users
WHERE CAST(?1 AS BOOLEAN) OR disabled_at IS NULL
ORDER BY created_at, id
`

func (q *Queries) ListUsers(ctx context.Context, includeDisabled bool) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, includeDisabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Scopes,
			&i.Root,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = ?, password_changed_at = ?, updated_at = ? WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash      string
	PasswordChangedAt int64
	UpdatedAt         int64
	ID                int64
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword,
		arg.PasswordHash,
		arg.PasswordChangedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE token_hash = ?
`

type TouchSessionParams struct {
	LastSeenAt int64
	TokenHash  []byte
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.TokenHash)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = ? WHERE id = ?
`

type TouchUserLoginParams struct {
	LastLoginAt sql.NullInt64
	ID          int64
}

func (q *Queries) TouchUserLogin(ctx context.Context, arg TouchUserLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchUserLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET scopes = ?, disabled_at = ?, updated_at = ? WHERE id = ?
`

type UpdateUserParams struct {
	Scopes     string
	DisabledAt sql.NullInt64
	UpdatedAt  int64
	ID         int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Scopes,
		arg.DisabledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
