// Package store opens the SQLite database that records API keys, print jobs
// and audit events. Queries are generated by sqlc into package dbq.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"os"
	"path"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/connordoman/thermal/internal/store/dbq"
	_ "modernc.org/sqlite" // pure Go driver, so the server builds without cgo
)

//go:embed migrations/*.sql
var migrations embed.FS

// Store is an open database.
type Store struct {
	*dbq.Queries
	DB *sql.DB

	// Created reports whether the database file did not exist before Open.
	Created bool
}

// Open opens the database at file, creating and migrating it as needed.
func Open(ctx context.Context, file string) (*Store, error) {
	_, err := os.Stat(file)
	created := errors.Is(err, fs.ErrNotExist)

	q := url.Values{}
	for _, p := range []string{
		"journal_mode(WAL)",
		"busy_timeout(5000)",
		"foreign_keys(ON)",
		"synchronous(NORMAL)",
	} {
		q.Add("_pragma", p)
	}
	db, err := sql.Open("sqlite", "file:"+file+"?"+q.Encode())
	if err != nil {
		return nil, err
	}
	// SQLite allows one writer at a time. A single connection serialises
	// access in Go instead of returning SQLITE_BUSY, and is plenty for a
	// print server.
	db.SetMaxOpenConns(1)

	if err := migrate(ctx, db); err != nil {
		db.Close()
		return nil, err
	}
	return &Store{Queries: dbq.New(db), DB: db, Created: created}, nil
}

// Close closes the database.
func (s *Store) Close() error { return s.DB.Close() }

// migrate applies migrations/NNNN_*.sql files newer than PRAGMA user_version.
func migrate(ctx context.Context, db *sql.DB) error {
	var version int
	if err := db.QueryRowContext(ctx, "PRAGMA user_version").Scan(&version); err != nil {
		return fmt.Errorf("store: reading schema version: %w", err)
	}
	names, err := fs.Glob(migrations, "migrations/*.sql")
	if err != nil {
		return err
	}
	slices.Sort(names)
	for _, name := range names {
		n, err := strconv.Atoi(strings.SplitN(path.Base(name), "_", 2)[0])
		if err != nil {
			return fmt.Errorf("store: migration %s has no numeric prefix", name)
		}
		if n <= version {
			continue
		}
		body, err := migrations.ReadFile(name)
		if err != nil {
			return err
		}
		tx, err := db.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, string(body)); err != nil {
			tx.Rollback()
			return fmt.Errorf("store: applying %s: %w", name, err)
		}
		if _, err := tx.ExecContext(ctx, fmt.Sprintf("PRAGMA user_version = %d", n)); err != nil {
			tx.Rollback()
			return err
		}
		if err := tx.Commit(); err != nil {
			return err
		}
		version = n
	}
	return nil
}

// Now returns the current time in the database's timestamp format.
func Now() int64 { return time.Now().UnixMilli() }

// Millis converts t to the database's timestamp format.
func Millis(t time.Time) int64 { return t.UnixMilli() }

// Time converts a database timestamp to a time, or nil if it is not set.
func Time(v sql.NullInt64) *time.Time {
	if !v.Valid {
		return nil
	}
	t := time.UnixMilli(v.Int64).UTC()
	return &t
}

// NullString returns s as a sql.NullString, NULL when empty.
func NullString(s string) sql.NullString { return sql.NullString{String: s, Valid: s != ""} }

// NullInt returns v as a sql.NullInt64, NULL when zero.
func NullInt(v int64) sql.NullInt64 { return sql.NullInt64{Int64: v, Valid: v != 0} }
